describe('Form inputs and links', () => {
    it ('Can navigate to the site',() => {
        cy.visit('http://localhost:3000')
        cy.url().should('include', 'localhost')
    })

    it ('Button is disabled', () => {
        cy.get('button')
          .should('be.disabled')
    })

    it ('Can type a name', () => {
        cy.get('input[name="first_name"]')
          .type('Boaty Mcboatface')
          .should('have.value', 'Boaty Mcboatface')
    })

    it ('Can type an email', () => {
        cy.get('input[name="email"]')
        .type('boaty@mcboatface.com')
        .should('have.value', 'boaty@mcboatface.com')
    })

    it ('Can type password', () => {
        cy.get('input[name="password"]')
          .type('SuperSecretBoatyPassword')
          .should('have.value', 'SuperSecretBoatyPassword')
    })

    it ('Can check Tos box', () => {
        cy.get('input[name="tos"]')
        .click()
        .should('be.checked')
    })

    it ('Submit button works now', () => {
        cy.get('button')
        .should('not.be.disabled')
    })

    it ('Tos link works', () => {
        cy.get('a').click().url()
        .should('include', 'tos')
    })

    it ('Return link works', () => {
        cy.get('a').click().url()
        .should('not.include', 'tos')
    })
})

describe('Form validation', () => {
    it('validates username', () => {
        cy.visit('http://localhost:3000')
        cy.contains('The username must be at least five characters long')
        .should('not.exist')
        cy.get('input[name="first_name"').type('B')
        cy.contains('The username must be at least five characters long')
        .should('exist')
        cy.get('input[name="first_name"').type('o')
        cy.contains('The username must be at least five characters long')
        .should('exist')
        cy.get('input[name="first_name"').type('a')
        cy.contains('The username must be at least five characters long')
        .should('exist')
        cy.get('input[name="first_name"').type('t')
        cy.contains('The username must be at least five characters long')
        .should('exist')
        cy.get('input[name="first_name"').type('y')
        cy.contains('The username must be at least five characters long')
        .should('not.exist')
    })

    it('validates email', () => {
        // cy.visit('http://localhost:3000')
        // cy.contains('The email is a required field')
        // .should('not.exist')
        // cy.get('input[name="email"]').type('B')
        // cy.get('input[name="email"]').clear()
        // cy.contains('The email is a required field')
        // .should('exist')
        cy.visit('http://localhost:3000')
        cy.contains('The email must be a valid email address')
        .should('not.exist')
        cy.get('input[name="email"').type('b')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('o')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('a')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('t')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('@')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('b')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('.')
        cy.contains('The email must be a valid email address')
        .should('exist')
        cy.get('input[name="email"').type('c')
        cy.contains('The email must be a valid email address')
        .should('not.exist')
    })

    it('validates password', () => {
        cy.visit('http://localhost:3000')
        cy.contains('Password must be at least seven characters long')
        .should('not.exist')
        cy.get('input[name="password"').type('b')
        cy.contains('Password must be at least seven characters long')
        .should('exist')
        cy.get('input[name="password"').type('o')
        cy.contains('Password must be at least seven characters long')
        .should('exist')
        cy.get('input[name="password"').type('a')
        cy.contains('Password must be at least seven characters long')
        .should('exist')
        cy.get('input[name="password"').type('t')
        cy.contains('Password must be at least seven characters long')
        .should('exist')
        cy.get('input[name="password"').type('y')
        cy.contains('Password must be at least seven characters long')
        .should('exist')
        cy.get('input[name="password"').type('p')
        cy.contains('Password must be at least seven characters long')
        .should('exist')
        cy.get('input[name="password"').type('w')
        cy.contains('Password must be at least seven characters long')
        .should('not.exist')
    })

    it('Validates Tos', () => {
        cy.visit('http://localhost:3000')
        cy.contains('Terms of service must be accepted')
          .should('not.exist')
        cy.get('input[name="tos"]').click()
        cy.get('input[name="tos"]').click()
        cy.contains('Terms of service must be accepted')
          .should('exist')
    })
})

describe('Submitting user', () => {
    it('Able to submit user', () =>{
    cy.visit('http://localhost:3000')
    cy.get('input[name="first_name"]').type('Boaty Mcboatface')
    cy.get('input[name="email"]').type('boaty@mcboatface.com')
    cy.get('input[name="password"]').type('SuperSecretBoatyPassword')
    cy.get('input[name="tos"]').click()
    cy.get('button').click()
    cy.wait(500)
    cy.get('.user h2').contains('Boaty Mcboatface')
    })
})